subscriptions:
  - transport: sync
    commands:
      hlx.security.user.create_user:
        handler: Hlx\Security\User\Model\Task\CreateUser\CreateUserCommandHandler
      hlx.security.user.modify_user:
        handler: Hlx\Security\User\Model\Task\ModifyUser\ModifyUserCommandHandler
      hlx.security.user.proceed_user_workflow:
        handler: Hlx\Security\User\Model\Task\ProceedUserWorkflow\ProceedUserWorkflowCommandHandler
      hlx.security.user.set_user_password:
        handler: Hlx\Security\User\Model\Task\SetUserPassword\SetUserPasswordCommandHandler
