subscriptions:
  - transport: sync
    commands:
      hlx.security.user.register_user:
        handler: Hlx\Security\User\Model\Task\RegisterUser\RegisterUserCommandHandler
      hlx.security.user.register_oauth_user:
        handler: Hlx\Security\User\Model\Task\RegisterOauthUser\RegisterOauthUserCommandHandler
      hlx.security.user.update_oauth_user:
        handler: Hlx\Security\User\Model\Task\UpdateOauthUser\UpdateOauthUserCommandHandler
      hlx.security.user.modify_user:
        handler: Hlx\Security\User\Model\Task\ModifyUser\ModifyUserCommandHandler
      hlx.security.user.verify_user:
        handler: Hlx\Security\User\Model\Task\VerifyUser\VerifyUserCommandHandler
      hlx.security.user.proceed_user_workflow:
        handler: Hlx\Security\User\Model\Task\ProceedUserWorkflow\ProceedUserWorkflowCommandHandler
      hlx.security.user.start_set_user_password:
        handler: Hlx\Security\User\Model\Task\SetUserPassword\StartSetUserPasswordCommandHandler
      hlx.security.user.set_user_password:
        handler: Hlx\Security\User\Model\Task\SetUserPassword\SetUserPasswordCommandHandler
      hlx.security.user.logout_user:
        handler: Hlx\Security\User\Model\Task\LogoutUser\LogoutUserCommandHandler
