#
# Connections that are used for the Security crate's UserType.
---
storage_writers:
  hlx.security.user::domain_event::event_source::writer:
    class: Honeybee\Infrastructure\DataAccess\Storage\CouchDb\EventStream\EventStreamAppender
    connection: hlx.security.event_source

storage_readers:
  hlx.security.user::event_stream::event_source::reader:
    class: Honeybee\Infrastructure\DataAccess\Storage\CouchDb\EventStream\EventStreamReader
    connection: hlx.security.event_source
    settings:
      design_doc: hlx-security-user

  hlx.security.user::domain_event::event_source::reader:
    class: Honeybee\Infrastructure\DataAccess\Storage\CouchDb\DomainEvent\DomainEventReader
    connection: hlx.security.event_source
    settings:
      design_doc: hlx-security-user

units_of_work:
  hlx.security.user::domain_event::event_source::unit_of_work:
    class: Honeybee\Infrastructure\DataAccess\UnitOfWork\UnitOfWork
    event_reader: hlx.security.user::event_stream::event_source::reader
    event_writer: hlx.security.user::domain_event::event_source::writer
    dependencies:
      aggregate_root_type: Hlx\Security\User\Model\Aggregate\UserType