#
# Security specific connections.
---
hlx.security.event_source:
  class: Honeybee\Infrastructure\DataAccess\Connector\GuzzleConnector
  settings:
    host: 127.0.0.1
    port: 5984
    transport: http
    database: ${project.database.prefix}%2Bhlx-security
    status_test: /
