#
# Connections that are used within the Security crate.
---
storage_writers:
  hlx.security::version_list::event_source::writer:
    class: Honeybee\Infrastructure\DataAccess\Storage\CouchDb\StructureVersionList\StructureVersionListWriter
    connection: hlx.security.event_source

  hlx.security::version_list::view_store::writer:
    class: Honeybee\Infrastructure\DataAccess\Storage\Elasticsearch\StructureVersionList\StructureVersionListWriter
    connection: honeybee.view_store
    settings:
      index: ${project.database.prefix}.hlx-security
      type: version_list

storage_readers:
  hlx.security::version_list::event_source::reader:
    class: Honeybee\Infrastructure\DataAccess\Storage\CouchDb\StructureVersionList\StructureVersionListReader
    connection: hlx.security.event_source

  hlx.security::version_list::view_store::reader:
    class: Honeybee\Infrastructure\DataAccess\Storage\Elasticsearch\StructureVersionList\StructureVersionListReader
    connection: honeybee.view_store
    settings:
      index: ${project.database.prefix}.hlx-security
      type: version_list