#
# Connections that are used within the SystemAccount crate.
---
storage_writers:
  foh.system_account::version_list::event_source::writer:
    class: Honeybee\Infrastructure\DataAccess\Storage\CouchDb\StructureVersionList\StructureVersionListWriter
    connection: foh.system_account.event_source

  foh.system_account::version_list::view_store::writer:
    class: Honeybee\Infrastructure\DataAccess\Storage\Elasticsearch\StructureVersionList\StructureVersionListWriter
    connection: honeybee.view_store
    settings:
      index: foh-system_account
      type: version_list

storage_readers:
  foh.system_account::version_list::event_source::reader:
    class: Honeybee\Infrastructure\DataAccess\Storage\CouchDb\StructureVersionList\StructureVersionListReader
    connection: foh.system_account.event_source

  foh.system_account::version_list::view_store::reader:
    class: Honeybee\Infrastructure\DataAccess\Storage\Elasticsearch\StructureVersionList\StructureVersionListReader
    connection: honeybee.view_store
    settings:
      index: foh-system_account
      type: version_list
