#
# Connections that are used within the Security crate.
---
storage_writers:
  hlx.security::version_list::event_source::writer:
    class: Honeybee\CouchDb\Storage\StructureVersionList\StructureVersionListWriter
    connection: hlx.security.event_source

  hlx.security::version_list::view_store::writer:
    class: Honeybee\Elasticsearch2\Storage\StructureVersionList\StructureVersionListWriter
    connection: honeybee.view_store
    settings:
      index: ${project.database.prefix}.hlx-security
      type: version_list

storage_readers:
  hlx.security::version_list::event_source::reader:
    class: Honeybee\CouchDb\Storage\StructureVersionList\StructureVersionListReader
    connection: hlx.security.event_source

  hlx.security::version_list::view_store::reader:
    class: Honeybee\Elasticsearch2\Storage\StructureVersionList\StructureVersionListReader
    connection: honeybee.view_store
    settings:
      index: ${project.database.prefix}.hlx-security
      type: version_list