#
# SystemAccount migration targets
---
foh.system_account::migration::event_source:
  active: true
  settings:
    version_list_reader: foh.system_account::version_list::event_source::reader
    version_list_writer: foh.system_account::version_list::event_source::writer
    target_connection: foh.system_account.event_source
  migration_loader:
    class: Honeybee\Infrastructure\Migration\FileSystemLoader
    settings:
      directory: ${project.dir}/app/crates/SystemAccount/migration/couchdb

foh.system_account::migration::view_store:
  active: true
  settings:
    version_list_reader: foh.system_account::version_list::view_store::reader
    version_list_writer: foh.system_account::version_list::view_store::writer
    target_connection: honeybee.view_store
    index: foh-system_account
  migration_loader:
    class: Honeybee\Infrastructure\Migration\FileSystemLoader
    settings:
      directory: ${project.dir}/app/crates/SystemAccount/migration/elasticsearch
