#
# Security migration targets
---
hlx.security::migration::event_source:
  active: true
  settings:
    version_list_reader: hlx.security::version_list::event_source::reader
    version_list_writer: hlx.security::version_list::event_source::writer
    target_connection: hlx.security.event_source
  migration_loader:
    class: Honeybee\Infrastructure\Migration\FileSystemLoader
    settings:
      directory: ${project.dir}/vendor/honeylex/hlx-security/migration/couchdb

hlx.security::migration::view_store:
  active: true
  settings:
    version_list_reader: hlx.security::version_list::view_store::reader
    version_list_writer: hlx.security::version_list::view_store::writer
    target_connection: honeybee.view_store
    index: ${project.database.prefix}.hlx-security
  migration_loader:
    class: Honeybee\Infrastructure\Migration\FileSystemLoader
    settings:
      directory: ${project.dir}/vendor/honeylex/hlx-security/migration/elasticsearch