#
# service configuration for the Security crate
---
hlx.security.user.auth_service:
  class: Hlx\Security\Service\StandardAuthService
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\DefaultProvisioner
    settings:
      alias: Honeybee\Infrastructure\Security\Auth\AuthServiceInterface

hlx.security.user.user_service:
  class: Hlx\Security\Service\UserService
  settings:
    stateless: false
  provisioner:
    class: Hlx\Security\Service\Provisioner\UserServiceProvisioner
    settings:
      app_key: user.service
      share: true
      alias: Symfony\Component\Security\Core\User\UserProviderInterface
