#
# service configuration for the SystemAccount crate
---
foh.system_account.user.hello_service:
  class: Foh\SystemAccount\User\HelloService
  options:
    greetings:
      - Hello world!
      - Honeylux says hello!
      - Welcome to your Honeylux app boilerplate!
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\DefaultProvisioner
    settings:
      share: true
