#
# Services configuration for the Security crate
---
hlx.security.user_provider:
  class: Hlx\Security\Service\UserProvider
  settings:
  provisioner:
    class: Hlx\Security\Service\Provisioner\UserProviderProvisioner

hlx.security.account_service:
  class: Hlx\Security\Service\AccountService
  provisioner:
    class: Honeylex\Service\Provisioner\DefaultProvisioner

hlx.security.password_encoder:
  class: Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder
  provisioner:
    class: Honeylex\Service\Provisioner\SilexServiceProvisioner
    settings:
      app_key: security.encoder.bcrypt
      share: true
      alias: Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface

hlx.security.token_storage:
  class: Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage
  provisioner:
    class: Honeylex\Service\Provisioner\SilexServiceProvisioner
    settings:
      app_key: security.token_storage
      share: true
      alias: Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface

hlx.security.authorization_checker:
  class: Symfony\Component\Security\Core\Authorization\AuthorizationChecker
  provisioner:
    class: Honeylex\Service\Provisioner\SilexServiceProvisioner
    settings:
      app_key: security.authorization_checker
      share: true
      alias: Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface

hlx.security.mail_service:
  class: Hlx\Security\Service\MailService
  provisioner:
    class: Honeylex\Service\Provisioner\DefaultProvisioner
  options:
    from_email: ${project.email.from_email}
    from_name: ${project.email.from_name}
    sender_email: ${project.email.sender_email}
    sender_name: ${project.email.sender_name}
    reply_email: ${project.email.reply_email}
    reply_name: ${project.email.reply_name}
