#
# service configuration for the Security crate
---
hlx.security.user.auth_service:
  class: Hlx\Security\Service\StandardAuthService
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\DefaultProvisioner
    settings:
      alias: Honeybee\Infrastructure\Security\Auth\AuthServiceInterface

hlx.security.user.registration_service:
  class: Hlx\Security\Service\StandardRegistrationService
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\DefaultProvisioner
    settings:
      alias: Hlx\Security\Service\RegistrationServiceInterface

hlx.security.user.user_service:
  class: Hlx\Security\Service\UserService
  provisioner:
    class: Hlx\Security\Service\Provisioner\UserServiceProvisioner
    settings:
      app_key: user.service
      share: true
      logout_handler: Hlx\Security\Controller\LoginController
      alias: Symfony\Component\Security\Core\User\UserProviderInterface

hlx.security.user.token_storage:
  class: Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\SilexServiceProvisioner
    settings:
      app_key: security.token_storage
      share: true
      alias: Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface
