#
# Services configuration for the Security crate
---
hlx.security.authentication_service:
  class: Hlx\Security\Service\AuthenticationService
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\DefaultProvisioner
    settings:
      alias: Honeybee\Infrastructure\Security\Auth\AuthServiceInterface

hlx.security.account_service:
  class: Hlx\Security\Service\AccountService
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\DefaultProvisioner

hlx.security.user_service:
  class: Hlx\Security\Service\UserService
  provisioner:
    class: Hlx\Security\Service\Provisioner\UserServiceProvisioner

hlx.security.token_storage:
  class: Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\SilexServiceProvisioner
    settings:
      app_key: security.token_storage
      share: true
      alias: Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface

hlx.security.mail_service:
  class: Hlx\Security\Service\MailService
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\DefaultProvisioner
  options:
    from_email: ${project.email.from_email}
    from_name: ${project.email.from_name}
    sender_email: ${project.email.sender_email}
    sender_name: ${project.email.sender_name}
    reply_email: ${project.email.reply_email}
    reply_name: ${project.email.reply_name}
