#
# service configuration for the SystemAccount crate
---
foh.system_account.user.auth_service:
  class: Foh\SystemAccount\Service\StandardAuthService
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\DefaultProvisioner
    settings:
      alias: Honeybee\Infrastructure\Security\Auth\AuthServiceInterface

foh.system_account.user.user_service:
  class: Foh\SystemAccount\Service\UserService
  settings:
    stateless: false
  provisioner:
    class: Foh\SystemAccount\Service\Provisioner\UserServiceProvisioner
    settings:
      app_key: user.service
      share: true
      alias: Symfony\Component\Security\Core\User\UserProviderInterface
