en:
  messages:
    'Login': Login
    'Logout': Logout
    'Forgot your password?': 'Forgot your password?'
    'My Account': 'My Account'
    'Register': Register
  email:
    'Verification required': 'Verification required'
    'Password setting instructions': 'Password setting instructions'
    'Your password was set': 'Your password was set'
  errors:
    'Username could not be found.': 'User could not be found'
    'Invalid credentials.': 'User could not be found'
  role:
    'administrator': 'Administrator'
    'user': 'User'

de:
  messages:
    'Login': Anmeldung
    'Logout': Ausloggen
    'Forgot your password?': 'Haben Sie Ihr Passwort vergessen?'
    'My Account': 'Mein Konto'
    'Register': Anmelden
  errors:
    'Username could not be found.': 'Benutzer wurde nicht gefunden'
    'Invalid credentials.': 'Benutzer wurde nicht gefunden'
  email:
    'Verification required': 'Bestätigung notwendig'
    'Password setting instructions': 'Passwort-Einstellung Anweisungen'
    'Your password was set': 'Ihr Passwort wurde gesetzt'